name: Build Pre-Release

on:
  push:
    branches: [ schlop ]
    paths-ignore:
      - '**.md'
      - '**/ISSUE_TEMPLATE/**'
      - '**.json'
      - '.gitignore'
      - '.gitattributes'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Get short commit hash
      id: get-hash
      shell: bash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Write commit message to release notes file
      shell: bash
      run: git log -1 --pretty=%B > release-body.txt

    - name: Replace ToolVersion with pre-release version
      run: |
        $content = Get-Content -Path "${{github.workspace}}/XAU/ViewModels/Pages/HomeViewModel.cs" -Raw
        $content = $content -replace 'public static string ToolVersion = "EmptyDevToolVersion";', 'public static string ToolVersion = "PRE-${{ steps.get-hash.outputs.hash }}";'
        Set-Content -Path "${{github.workspace}}/XAU/ViewModels/Pages/HomeViewModel.cs" -Value $content
        $mw = Get-Content -Path "${{github.workspace}}/XAU/ViewModels/Windows/MainWindowViewModel.cs" -Raw
        $mw = $mw -replace 'Tool Version: \{System\.Reflection\.Assembly\.GetExecutingAssembly\(\)\.GetName\(\)\.Version\}', 'Tool Version: PRE-${{ steps.get-hash.outputs.hash }}'
        Set-Content -Path "${{github.workspace}}/XAU/ViewModels/Windows/MainWindowViewModel.cs" -Value $mw

    - name: Restore dependencies
      run: dotnet restore /p:EnableWindowsTargeting=true

    - name: Build
      run: dotnet publish XAU.sln -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true /p:PublishReadyToRun=false /p:IncludeAllContentForSelfExtract=true /p:EnableWindowsTargeting=true -o ./publish

    - name: Copy .exe file to workspace
      run: |
        Remove-Item -Path "${{github.workspace}}/XAU.exe" -ErrorAction Ignore
        Copy-Item -Path "./publish/XAU.exe" -Destination "${{github.workspace}}/XAU.exe"

    - name: Create GitHub pre-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "PRE-${{ steps.get-hash.outputs.hash }}" "${{github.workspace}}/XAU.exe" `
          --title "PRE-${{ steps.get-hash.outputs.hash }}" `
          --notes-file release-body.txt `
          --target schlop `
          --prerelease `
          --repo ${{ github.repository }}
